#!/bin/bash
set -e

if [ -z "$TYPE" ]
  then TYPE=release
fi
export PATH="$(realpath "$(dirname "$0")/../bin/$TYPE/"):$PATH"

ffmpeg=
if [ "$1" == "--ffmpeg" ]
  then ffmpeg=ffmpeg; shift
fi

command="$1"; shift
pipeline="$1"

if [ -z "$pipeline" ] && [ -z "$ffmpeg" ]
then pipeline="videoconvert ! autovideosink sync=false"
fi

if [ -z "$FPS" ]; then FPS=60; fi

(
  set -e
  i=0
  first=1
  while [ -z "$COUNT" ] || [ "$i" -lt "$COUNT" ]
  do
    (
      eval "$command"
    ) | (
      # Keep only the first bmp header, strip the other ones
      if [ -n "$first" ]
        then export $(bmpinfo --dump-input)
        else export $(bmpinfo)
      fi
      dd status=none iflag=count_bytes,fullblock count=$cmp_image_data_size
    ) 9>&1
    i=$((i + 1))
    first=
  done
) | (
  export $(bmpinfo)
  if [ "$ffmpeg" ]
  then "$ffmpeg" -f rawvideo -video_size "$hdr_width"x"$hdr_height" -framerate "$FPS" -pix_fmt "$cmp_fformat" -i - -vf vflip $pipeline
  else gst-launch-1.0 -q -e fdsrc \
   ! rawvideoparse width="$hdr_width" height="$hdr_height" format="GST_VIDEO_FORMAT_$cmp_gformat" framerate="$FPS"/1 \
   ! videoflip method=vertical-flip \
   ! $pipeline
  fi
)
